config/routes.rb
Rails.application.routes.draw do
  get '/users/:id/amazon', to: 'users#amazon'

  get '/tours/:id/amazon', to: 'tours#amazon'

  get "/tours/:id/mobiletour", to: 'tours#mobiletour'

  get '/tours/:id/locations/:id/comment', to: 'comments#content'
  get '/tours/:id/locations/:id/content', to: 'locations#content'

  get '/tours/:id/locations/:id/video_amazon', to: 'locations#video_amazon'
  get '/tours/:id/locations/:id/image_amazon', to: 'locations#image_amazon'
  get '/tours/:id/locations/:id/audio_amazon', to: 'locations#audio_amazon'

  get '/tours/:id/locations/:id/comments/:id/image_amazon', to: 'comments#image_amazon'

  get '/tours/:id/locations/:id/comments/:id/imageupload', to: 'comments#imageupload'

  get 'image/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  root 'home#index'
  resources :users do
    resources :badges
  end

  resources :friendships
  post '/friend_request', to: 'friendships#friend_request'

  resources :friendable do
    member do put 'friend_request' end end

  resources :tours do
    resources :locations
    resources :comments
    resources :reviews
    resources :tags
  end

  resources :locations do
    resources :comments
  end
  resources :tags

  resources :searches

  authenticate :user do
    resources :tours
  end

  get "cities/:id", to: 'searches#show_city'

  post '/participate', to: 'tours#participate'
  post '/quit', to: 'tours#quit'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/tours/:id/directions", to: 'tours#get_directions'
  post "/tours/:id/locations/:id/checkin", to: 'locations#checkin'
  post "/tours/:id/locations/:id/checkinstatic", to: 'locations#checkin_static'
  post "publish", to: 'tours#publish'

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
	before_action :authenticate_user!
	before_action :set_friend, only: [:new]
	
	def new
	end

	def create
    recipients = User.where(name: conversation_params[:recipients])
    conversation = current_user.send_message(recipients, conversation_params[:body], conversation_params[:subject]).conversation
    flash[:success] = "Your message was successfully sent!"
    redirect_to conversation_path(conversation)
  end

  def show
    @receipts = conversation.receipts_for(current_user)
    # mark conversation as read
    conversation.mark_as_read(current_user)
  end

	def reply
		current_user.reply_to_conversation(conversation, message_params[:body])
		redirect_to conversation_path(conversation)
	end

	def trash
		conversation.move_to_trash(current_user)
		redirect_to mailbox_inbox_path
	end

	def untrash
		conversation.untrash(current_user)
		redirect_to mailbox_inbox_path
	end

  private

	def message_params
    params.require(:message).permit(:body, :subject)
  end

  def conversation_params
    params.require(:conversation).permit(:subject, :body, :recipients)
  end

	def set_friend
		@friend = User.find(params[:friend_id]) if !params[:friend_id].nil?
	end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<div class="media">
  <div class="media-left">
    <!-- <a href="#"> -->
      <!-- <img class="media-object" src="http://placehold.it/64x64" alt="..."> -->
    <!-- </a> -->
  </div>
  <div class="media-body">
    <h4 class="media-heading">
      <%= conversation.originator.name %> <br>
      <small><b>Subject: </b><%= conversation.subject %></small><br>
      <small><b>Date: </b><%=  conversation.messages.last.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
    </h4>
    <%= truncate conversation.messages.last.body, length: 145 %>
    <%= link_to "View", conversation_path(conversation)  %>
  </div>
  <div class="col-md-6 text-right">
   <% if conversation.is_trashed?(current_user) %>
       <%= link_to 'Untrash', untrash_conversation_path(conversation), class: 'btn btn-info', method: :post %>
   <% else %>
       <%= link_to 'Move to trash', trash_conversation_path(conversation), class: 'btn btn-danger', method: :post,
                   data: {confirm: 'Are you sure?'} %>
   <% end %>
 </div>
</div>

app/views/conversations/_form.html.erb
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<%= stylesheet_link_tag 'jquery.tagit' %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>

  <%= javascript_include_tag 'tag-it.js' %>
<%= form_for :conversation, url: :conversations, html: { class: "" } do |f| %>
    <div class="form-group">
      <%= f.label :recipients %>
      <% if @friend.nil? %>
        <%= f.text_field :recipients, placeholder: "Friends Name", id: "autocomplete-friend" %>
        <% else %>
        <%# binding.pry %>
        <%=  %>
        <%= f.text_field :recipients, value: "#{@friend.name}" %>
        <% end %>
      <%# f.text_field(:recipients, current_user.friends.collect {|p| [ p.name, p.id ] }, {}, { multiple: true , class: "form-control" })%>
    </div>
    <div class="form-group">
      <%= f.label :subject %>
      <%= f.text_field :subject, placeholder: "Subject", id: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :message %>
      <%= f.text_area :body, class: 'form-control',placeholder: "Type your message here", rows: 4  %>
    </div>
    <%= f.submit "Send Message", class: "btn btn-success" %>


<% end %>

<script>
$( "#autocomplete-friend" ).autocomplete({
  source: <%= raw current_user.friends.collect{|x| x.name} %>
});
</script>

app/views/conversations/_messages.html.erb
<% @receipts.each do |receipt| %>
    <% message = receipt.message %>
    <div class="media">
      <div class="media-left">
        <!-- user avators can go here -->
        <!-- <a href="#">
          <img class="media-object" src="http://placehold.it/64x64" alt="...">
        </a> -->
      </div>
      <div class="media-body">
        <h4 class="media-heading">
          <%= message.sender.name %> <br>
          <small><b>Subject: </b><%= message.subject %></small><br>
          <small><b>Date: </b><%=  message.created_at.strftime("%A, %b %d, %Y at %I:%M%p") %></small>
        </h4>
        <%= message.body %>
      </div>
    </div>
<% end %>

app/views/conversations/new.html.erb
<%= render partial: 'mailbox/folder_view', locals: { is_conversation: true } %>

app/views/conversations/show.html.erb
<div class="row">
  <div class="spacer"></div>
  <div class="col-md-12">
    <%= link_to "Compose", new_conversation_path, class: "btn btn-success" %>
    <div class="spacer"></div>
  </div>

  <div class="col-md-4">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render 'mailbox/folders' %>
      </div>
    </div>
  </div>

  <div class="col-md-8">
    <div class="panel panel-default">
      <div class="panel-body">
        <%= render partial: 'messages' %>
      </div>
    </div>
  </div>

	<div class="panel-footer">
	        <!-- Reply Form -->
	        <%= form_for :message, url: reply_conversation_path(conversation) do |f| %>
	            <div class="form-group">
	              <%= f.text_area :body, placeholder: "Reply Message", rows: 4, class: "form-control" %>
	            </div>
	            <%= f.submit "Reply", class: 'btn btn-danger pull-right' %>
	        <% end %>
	        <div class="clearfix"></div>
	      </div>
	    </div>
	  </div>

</div>