config/routes.rb
Rails.application.routes.draw do
  get '/users/:id/amazon', to: 'users#amazon'

  get '/tours/:id/amazon', to: 'tours#amazon'

  get "/tours/:id/mobiletour", to: 'tours#mobiletour'

  get '/tours/:id/locations/:id/comment', to: 'comments#content'
  get '/tours/:id/locations/:id/content', to: 'locations#content'

  get '/tours/:id/locations/:id/video_amazon', to: 'locations#video_amazon'
  get '/tours/:id/locations/:id/image_amazon', to: 'locations#image_amazon'
  get '/tours/:id/locations/:id/audio_amazon', to: 'locations#audio_amazon'

  get '/tours/:id/locations/:id/comments/:id/image_amazon', to: 'comments#image_amazon'

  get '/tours/:id/locations/:id/comments/:id/imageupload', to: 'comments#imageupload'

  get 'image/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  root 'home#index'
  resources :users do
    resources :badges
  end

  resources :friendships
  post '/friend_request', to: 'friendships#friend_request'

  resources :friendable do
    member do put 'friend_request' end end

  resources :tours do
    resources :locations
    resources :comments
    resources :reviews
    resources :tags
  end

  resources :locations do
    resources :comments
  end
  resources :tags

  resources :searches

  authenticate :user do
    resources :tours
  end

  get "cities/:id", to: 'searches#show_city'

  post '/participate', to: 'tours#participate'
  post '/quit', to: 'tours#quit'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/tours/:id/directions", to: 'tours#get_directions'
  post "/tours/:id/locations/:id/checkin", to: 'locations#checkin'
  post "/tours/:id/locations/:id/checkinstatic", to: 'locations#checkin_static'
  post "publish", to: 'tours#publish'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :tours, foreign_key: "guide_id", dependent: :destroy
  has_many :categories, through: :category_users
  has_many :category_tags, through: :categories
  has_many :tags, through: :category_tags
  has_many :locations, through: :tours
  has_many :guide_comments
  has_many :comments, through: :guide_comments, foreign_key: "guide_id"

  has_many :guideratings, foreign_key: "guide_id"

  has_many :images, foreign_key: "guide_id"
  has_many :images, foreign_key: "participant_id"


  has_many :audios, foreign_key: "guide_id"
  has_many :audios, foreign_key: "participant_id"

  has_many :videos, foreign_key: "guide_id"
  has_many :videos, foreign_key: "participant_id"

  has_many :participant_tours, foreign_key: "participant_id"
  has_many :trips, through: :participant_tours, source: :tour
  has_many :location_participants, foreign_key: "participant_id"
  has_many :places, through: :location_participants, source: :location
  has_many :reviews, through: :tours, foreign_key: "participant_id"

  has_many :participant_locations, foreign_key: "participant_id"
  has_many :checked_in_locations, through: :participant_locations, source: :location, foreign_key: "participant_id"

  has_many :badge_users
  has_many :badges, through: :badge_users

    has_many :friendships
    has_many :passive_friendships, :class_name => "Friendship", :foreign_key => "friend_id"

    has_many :active_friends, -> { where(friendships: { approved: true}) }, :through => :friendships, :source => :friend
    has_many :passive_friends, -> { where(friendships: { approved: true}) }, :through => :passive_friendships, :source => :user
    has_many :pending_friends, -> { where(friendships: { approved: false}) }, :through => :friendships, :source => :friend
    has_many :requested_friendships, -> { where(friendships: { approved: false}) }, :through => :passive_friendships, :source => :user





  mount_uploader :image, ImageUploader

  validates :name, presence: true
  validates :email, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  devise :omniauthable, :omniauth_providers => [:facebook]


  acts_as_messageable

  def friends
    active_friends | passive_friends
  end


  def mailboxer_name
   self.name
  end

  def mailboxer_email(object)
    self.email
  end

  def checkin_static(location)
    checked_in_locations << location
  end

  def checkin(location, coords)
    if location.lat.to_f.round(2) == coords["latitude"].to_f.round(2) && location.lng.to_f.round(2) == coords["longitude"].to_f.round(2)
      checked_in_locations << location
    else
      "You are not in the right location"
    end
  end

  def self.from_omniauth(auth)
       where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
         user.provider ||= auth.provider
         user.uid = auth.uid
         user.email = auth.info.email
         user.name = auth.extra.raw_info.first_name + " " + auth.extra.raw_info.last_name
         user.gender = auth.extra.raw_info.gender
         user.password = Devise.friendly_token[0,20]
    end
  end

  def get_badge
    badges_keys = ["guide", "review", "participant"]
    badges_keys.each do |badge|
      counter = set_count(badge)
      if counter > 0
        @badges = Badge.find_badge(badge)
        @badges.each do |badge|
          self.badges << badge if badge.requirement <= counter && !self.badges.include?(badge)
        end
      end
    end
  end


  def self.new_with_session(params, session)
   super.tap do |user|
     if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
       user.email = data["email"] if user.email.blank?
      end
    end
  end

  def set_average
    update(average_score: (guideratings.sum(:rating).to_f/guideratings.all.count.to_f).round(2) )
  end

  def set_count(badge_type)
    if badge_type == "guide"
      return counter = self.tours.count
    elsif badge_type == "review"
      return counter = Review.where(participant_id: self.id).count
    elsif badge_type == "participant"
      return counter = self.participant_tours.where(completed: true).count
    end
  end

end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

	def facebook
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
	    if @user.persisted?
	      sign_in_and_redirect @user, :event => :authentication #this will throw if @user is not activated
	      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
	    else
	      session["devise.facebook_data"] = request.env["omniauth.auth"]
	      redirect_to new_user_registration_url
	    end
  	end


    def edit
      binding.pry
    end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  def edit
    binding.pry
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # You can put the params you want to permit in the empty array.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  def edit
    binding.pry
  end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, except: [:show]
  before_action :set_user, only: [:show, :amazon]

  def edit
    binding.pry
  end

  def amazon
    binding.pry
    @user.images.create(image_url: params["key"])
    redirect_to @user
  end

  def show
    if @user.nil? || (!@user.nil? && !(@user.id == params["id"].to_i))
      @user = User.find(params["id"])
      @tours = @user.tours
      @trips = @user.trips
      render 'public_show'
    else
      @uploader = User.new.image
      @uploader.success_action_redirect = "/users/#{@user.id}/amazon"
      @tours = @user.tours
      @trips = @user.trips
      @user.get_badge
      render 'personal_show'
    end
  end

private
  def set_user
    @user = current_user
  end

  def reg_params
    params.require(:user).permit(:name, :image, :email, :location, :gender, :dob, :average_score)
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

app/views/users/personal_show.html.erb
<div class="userProfileAvatar">
<h2><%= @user.name %></h2>
<%= link_to 'Edit Profile', edit_user_registration_path if current_user.provider.nil? %><br>
<% if @user.images.count > 1 %>
  <%=image_tag("http://flatirontours.s3.amazonaws.com/#{@user.images.last.image_url}", size:"100x100")%>
  <% elsif @user.images.empty? %>
    <img src="http://abs.twimg.com/sticky/default_profile_images/default_profile_1.png">
    <% else %>
    <%= image_tag(@user.images.last.image_url, size:"100x100") %>
  <% end %>
</div>

<% if !@user.badges.empty? %>
<div class="userBadgesContainer">
    <% @user.badges.each do |badge| %>
      <div class="userBadge">
    <%= image_tag("#{badge.image_url}", size: "500x500") %><br>

    </div>
<% end %>
<% else %>
    <h4>You currently don't have any <%= link_to("badges!", user_badges_path(current_user)) %></h4>
</div>

<% end %>

  <div class="profileListContainer">
  <div class="userToursList">
      <h3>My Tours</h3>
      <% @tours.each do |guide| %>
        <%= link_to guide.title, tour_path(guide.id)  %><br>
        <% end %>
        </div>


        <div class="userCurrentToursList">
          <h3>Tours I'm On</h3>
        <% @trips.each do |participant| %>
          <%= participant.title %>
          <%= participant.description %><br><br>
          <%= link_to 'Go To Tour', tour_path(participant.id), class: "linkBtn" %><br>
        <% end %>
          </div>


      <div class="userFriendsList">
      <h3>Friends</h3>

        <% @user.friends.each do |friend| %>
          <%= link_to "#{friend.name}", user_path(friend) %>
          <% if current_user == @user %>
              | <%= link_to "Unfriend", friendship_path(:id => friend), :method => :delete %>
          <% end %>
      <% end %>
      </div>
      </div>


    <% if current_user == @user %>
      <% if !@user.requested_friendships.empty? %>
    <div id="frequest">
        <h4>Your Friend Request</h4>
        <% @user.requested_friendships.each do |request| %>
         <li>
          <%= link_to "#{request.name}", user_path(request) %><br>
          <%= link_to "Accept", friendship_path(:id => request), :method => "put" %> |
           <%= link_to "Decline", friendship_path(:id => request), :method => :delete %>
         </li><br>
       <% end %>
   </div>
     <% end %>
    <% end %>

app/views/users/private_show.html.erb
<%= form_for @user do |f| %>
  <div class="user">
    <div class="form">
      <h3>Tours I've Created</h3>
      <% current_user.tours.each do |guide| %>
        <li><%= link_to guide.title, tour_path(guide.id)  %><br>
        <% end %>
        <h3>Tours I'm On</h3>
        <% current_user.trips.each do |participant| %>
          <li><%= participant.title %>
          <li><%= participant.description %>
          <li><%= link_to 'Go To Tour', tour_path(participant.id) %><br>
        <% end %>
        <h3>My Friends</h3>
        <li>Friend 1
        <li>Friend 2
      </div>
  </div>
<% end %>

app/views/users/public_show.html.erb
<style>
    .thumb {
        background: url("http://ih1.redbubble.net/image.38250018.7772/flat,550x550,075,f.u1.jpg");
        width: 100px;
        height: 100px;
        border-radius: 50%;
        background-position: center center;
        background-size: cover;
        background-repeat: no-repeat;
    }
</style>

<div class="userProfileAvatar">
<% if @user.images.count > 1 %>
  <%=image_tag("http://flatirontours.s3.amazonaws.com/#{@user.images.last.image_url}", size:"100x100")%>
  <% elsif @user.images.empty? %>
    <img src="http://ih1.redbubble.net/image.38250018.7772/flat,550x550,075,f.u1.jpg">
    <% else %>
    <%= image_tag(@user.images.last.image_url, size:"100x100") %>
    <h2><%= @user.name %></h2>
  <% end %>
</div>

<% if !@user.badges.empty? %>
<div class="userBadgesContainer">
    <% @user.badges.each do |badge| %>
      <div class="userBadge">
    <%= image_tag("#{badge.image_url}", size: "300x300") %><br>

  </div>
<% end %>
<% else %>
    <h4>This user doesn't currently have any <%= link_to("badges!", user_badges_path(@user)) %></h4>
</div>

<% end %>

  <div class="profileListContainer">
  <div class="userToursList">
      <h3><%= @user.name %> Tours</h3>
      <% @tours.each do |guide| %>
        <%= link_to guide.title, tour_path(guide.id)  %><br>
        <% end %>
        </div>


        <div class="userCurrentToursList">
          <h3>Tours I'm On</h3>
        <% @trips.each do |participant| %>
          <%= participant.title %>
          <%= participant.description %>
          <%= link_to 'Go To Tour', tour_path(participant.id) %><br>
        <% end %>
          </div>


      <div class="userFriendsList">
      <h3>Friends</h3>

        <% @user.friends.each do |friend| %>
          <%= link_to "#{friend.name}", user_path(friend) %>
          <% if current_user == @user %>
              | <%= link_to "Remove", friendship_path(:id => friend), :method => :delete %>
          <% end %>
      <% end %>
      </div>
      </div>

app/views/users/show.html.erb
<%= form_for @user do |f| %>
  <div class="user">
    <div class="form">
      <h3>Tours I've Created</h3>
      <% current_user.tours.each do |guide| %>
        <li><%= link_to guide.title, tour_path(guide.id)  %><br>
        <% end %>
        <h3>Tours I'm On</h3>
        <% current_user.trips.each do |participant| %>
          <li><%= participant.title %>
          <li><%= participant.description %>
          <li><%= link_to 'Go To Tour', tour_path(participant.id) %><br>
        <% end %>
        <h3>My Friends</h3>
        <li>Friend 1
        <li>Friend 2
      </div>
  </div>
<% end %>