config/routes.rb
Rails.application.routes.draw do
  get '/users/:id/amazon', to: 'users#amazon'

  get '/tours/:id/amazon', to: 'tours#amazon'

  get "/tours/:id/mobiletour", to: 'tours#mobiletour'

  get '/tours/:id/locations/:id/comment', to: 'comments#content'
  get '/tours/:id/locations/:id/content', to: 'locations#content'

  get '/tours/:id/locations/:id/video_amazon', to: 'locations#video_amazon'
  get '/tours/:id/locations/:id/image_amazon', to: 'locations#image_amazon'
  get '/tours/:id/locations/:id/audio_amazon', to: 'locations#audio_amazon'

  get '/tours/:id/locations/:id/comments/:id/image_amazon', to: 'comments#image_amazon'

  get '/tours/:id/locations/:id/comments/:id/imageupload', to: 'comments#imageupload'

  get 'image/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  root 'home#index'
  resources :users do
    resources :badges
  end

  resources :friendships
  post '/friend_request', to: 'friendships#friend_request'

  resources :friendable do
    member do put 'friend_request' end end

  resources :tours do
    resources :locations
    resources :comments
    resources :reviews
    resources :tags
  end

  resources :locations do
    resources :comments
  end
  resources :tags

  resources :searches

  authenticate :user do
    resources :tours
  end

  get "cities/:id", to: 'searches#show_city'

  post '/participate', to: 'tours#participate'
  post '/quit', to: 'tours#quit'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/tours/:id/directions", to: 'tours#get_directions'
  post "/tours/:id/locations/:id/checkin", to: 'locations#checkin'
  post "/tours/:id/locations/:id/checkinstatic", to: 'locations#checkin_static'
  post "publish", to: 'tours#publish'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @search = Search.new
  end

  def show
    redirect_to user_registration_path
  end

  def greeting
    render :index
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<!-- <div class="eventImage">
  <div class="eventDescription">
    <div class="element"><h2></h2></div>
  </div>
</div> -->


<div class="citiesList">
<% City.all.each_with_index do |city, index| %>
      <div class="cityImage">
    <%= form_for :search, url: searches_path  do |f| %>
    <%= f.hidden_field :tags %>
    <%= f.hidden_field :city, :value => city.name %>
    <%= f.submit city.accent, :id => "city#{index}" %>
  <style>
    <%=  "#city#{index}" %>
    {
  background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(<%= city.image %>);
  background-color: black;
  font-size:35pt;
  color: white;
  height: 400px;
  width: 400px;
  /*background:url(<%= city.image %>) no-repeat center;*/
  background-size: 400px 400px;
  border: 0;
  cursor: pointer;
    }
  </style>

  <% end %>
      </div>
<% end %>

</div>

<div class="footerCredits">
  <h4>
    By Andrew Cabrera, Anton Halim, David Lorente and In Ho Hwang.
    <br>Created with ❤️ at Flatiron School.</h4>

  </h4>
</div>


  <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
  <script src="//code.jquery.com/jquery-1.10.2.js"></script>
  <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

  <script src="//ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
  <%= javascript_include_tag 'typed.js' %>
  <%# stylesheet_link_tag 'application.css.scss' %>

  <script>
  $(function(){
    $(".element").typed({
      strings: ["Created with ❤️", "Andrew Cabrera", "Anton Halim", "David Lorente", "In Ho Hwang"],
      typeSpeed: 0,
      backDelay: 500,
      loop: true,
      loopCount: true,
      cursorChar: "💴 💴 💴 💴",
      callback: function(){ foo(); },
      resetCallback: function() { newTyped(); }
    });
    $(".reset").click(function(){
        $("#typed").typed('reset');
    });
  });

  function newTyped(){ /* A new typed object */ }
  function foo(){ console.log("Callback"); }

  $( "#autocomplete-city" ).autocomplete({
    source: <%= raw City.pluck(:name) %>
  });
  $( "#autocomplete-tag" ).autocomplete({
    source: <%= raw Tag.pluck(:name) %>
});

</script>