config/routes.rb
Rails.application.routes.draw do
  get '/users/:id/amazon', to: 'users#amazon'

  get '/tours/:id/amazon', to: 'tours#amazon'

  get "/tours/:id/mobiletour", to: 'tours#mobiletour'

  get '/tours/:id/locations/:id/comment', to: 'comments#content'
  get '/tours/:id/locations/:id/content', to: 'locations#content'

  get '/tours/:id/locations/:id/video_amazon', to: 'locations#video_amazon'
  get '/tours/:id/locations/:id/image_amazon', to: 'locations#image_amazon'
  get '/tours/:id/locations/:id/audio_amazon', to: 'locations#audio_amazon'

  get '/tours/:id/locations/:id/comments/:id/image_amazon', to: 'comments#image_amazon'

  get '/tours/:id/locations/:id/comments/:id/imageupload', to: 'comments#imageupload'

  get 'image/new'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "registrations" }

  root 'home#index'
  resources :users do
    resources :badges
  end

  resources :friendships
  post '/friend_request', to: 'friendships#friend_request'

  resources :friendable do
    member do put 'friend_request' end end

  resources :tours do
    resources :locations
    resources :comments
    resources :reviews
    resources :tags
  end

  resources :locations do
    resources :comments
  end
  resources :tags

  resources :searches

  authenticate :user do
    resources :tours
  end

  get "cities/:id", to: 'searches#show_city'

  post '/participate', to: 'tours#participate'
  post '/quit', to: 'tours#quit'

  get "mailbox/inbox" => "mailbox#inbox", as: :mailbox_inbox
  get "mailbox/sent" => "mailbox#sent", as: :mailbox_sent
  get "mailbox/trash" => "mailbox#trash", as: :mailbox_trash

  resources :conversations do
    member do
      post :reply
      post :trash
      post :untrash
    end
  end

  get "/tours/:id/directions", to: 'tours#get_directions'
  post "/tours/:id/locations/:id/checkin", to: 'locations#checkin'
  post "/tours/:id/locations/:id/checkinstatic", to: 'locations#checkin_static'
  post "publish", to: 'tours#publish'

end

app/models/tour.rb
class Tour < ActiveRecord::Base
  belongs_to :category
  belongs_to :guide, class_name: "User"
  has_many :city_tours
  has_many :cities, through: :city_tours
  has_many :location_tours
  has_many :locations, through: :location_tours, dependent: :destroy
  has_many :comments
  has_many :reviews
  has_many :tag_tours
  has_many :tags, through: :tag_tours
  has_many :participant_tours
  has_many :participants, through: :participant_tours
  has_many :images
  has_many :audios
  has_many :videos

  mount_uploader :image, ImageUploader

  accepts_nested_attributes_for :tags, reject_if: lambda {|attributes| attributes['name'].blank?}
  accepts_nested_attributes_for :cities, reject_if: lambda {|attributes| attributes['name'].blank?}
  accepts_nested_attributes_for :comments, reject_if: lambda {|attributes| attributes['content'].blank?}

  validates :title, :description, presence: true


  def participate(user)
    self.participants << user
    self.locations.each {|location| user.places << location}
  end

  def quit(user)
    self.participants.delete(user)
    self.locations.each do |location|
      user.places.delete(location)
      user.checked_in_locations.delete(location)
    end
    user.trips.delete(self)
  end

  def progress(user)
    x = 0
    locations.each do |location|
      if user.checked_in_locations.include?(location)
        x += 1
      end
    end
    if x == locations.count
    user.participant_tours.find_by(self.id).update(completed: TRUE)
    completed(user)
    end
    x.to_f/locations.count.to_f
  end

  def completed(user)
    participant_tours.where(completed: TRUE)
  end

  def get_directions
    # binding.pry
  end

  def set_average
    update(average_score: (reviews.sum(:rating).to_f/reviews.count.to_f).round(2) )
  end

  def tag_name
    tags.try(:name)
  end

  def tag_name=(name)
    self.tags << Tag.find_or_create_by_name(name) if name.present?
  end

end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
	before_action :authenticate_user!, :except => [:show, :index]
  before_action :set_tour, only: [:participants_show, :show, :get_directions, :edit, :update, :destroy, :participate, :quit, :amazon, :publish, :mobiletour]

  def new
    @tour = Tour.new
  end

  def edit
  end

  def amazon
    @tour.images.create(image_url: params["key"])
    redirect_to @tour
  end

  def mobiletour
    @nextlocations = @tour.locations.select do |location|
      !current_user.checked_in_locations.include?(location)
    end
  end

  def create
    city = set_city
    if params["tour"]["cities_attributes"]["0"]["name"].empty?
      flash[:alert] = "You have to give a city."
      redirect_to(:back)
    elsif city.nil?
      flash[:alert] = "This city isn't currently available."
      redirect_to(:back)
    else
    @tour = Tour.new(tour_params)
    @tour.cities << city
		@tour.tags << set_tags
    current_user.tours << @tour
		# current_user.get_badge
    respond_to do |format|
      if @tour.save
        @uploader = Tour.new.image
        @uploader.success_action_redirect = "http://localhost:3000/tours/#{@tour.id}/amazon"
        format.html { render "imageupload", notice: 'Tour was successfully created.' }
        format.json { render action: 'show', status: :created, location: @tour }
      else
        format.html { render action: 'new' }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
    end
  end

  def show
		@comment = Comment.new
    @user = current_user
    if @tour.guide == current_user
      @location = Location.new
      render 'guide_show'
    elsif @tour.participants.include?(current_user)
      @progress = @tour.progress(@user)
      render 'participants_show'
    else
      render 'non_participants_show'
    end
  end

  def update
    respond_to do |format|
      city = set_city
      @tour.cities << city
      @tour.tags << set_tags
      if @tour.update(tour_params)
        format.html { redirect_to @tour, notice: 'Tour was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @tour.errors, status: :unprocessable_entity }
      end
    end
  end

	def participate
		user = User.find_by(id: params[:user_id])
		@tour.participate(user)
      redirect_to @tour
	end

	def quit
		user = User.find_by(id: params[:user_id])
		@tour.quit(user)
		redirect_to root_path
	end

  def get_directions
    @directions = @tour.get_directions
    render 'directions'
  end

	def publish
		@tour.update(published: true)
		redirect_to tour_path(@tour)
	end

private
  def tour_params
    params.require(:tour).permit(:title, :description, :category_id, :tour_id )
  end

  def set_city
    city = params.require(:tour).permit(:cities_attributes => [:id, :name])
    City.find_by(name: city["cities_attributes"]["0"]["name"])
  end

  def set_tags
    tags = params.require(:tour).permit(:tags_attributes => [:id, :name])["tags_attributes"]["0"]["name"].split(",")
    returntags = []
    tags.each do |tag|
      returntags << Tag.find_or_create_by(name: tag.downcase)
    end
    returntags.uniq
  end

  def set_tour
    @tour = Tour.find(params[:id])
  end
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/tours/directions.html.erb
<div class="tourBodyContainer">

<% @tour.locations.each_with_index do |location, i| %>
<% unless i >= @tour.locations.count-1 %>
<br>
<p id="demo"></p>
<h1><%= location.title %></h1> <button id="check" class="linkBtn" onclick="window.history.back()">Tour</button>

<p><%= location.address %></p>

<script>
var directionsDisplay<%= i %>;
var directionsService<%= i %> = new google.maps.DirectionsService();
var map<%= i %>;

function initialize() {
  directionsDisplay<%= i %> = new google.maps.DirectionsRenderer();
  var myMap<%= i %> = new google.maps.LatLng(<%= raw location.lat %>,<%= raw location.lng %>);
  var mapOptions<%= i %> = {
    zoom:15,
    center: myMap<%= i %>
  };
  map<%= i %> = new google.maps.Map(document.getElementById("map-canvas<%= i %>"), mapOptions<%= i %>);
    var marker<%= i %> = new google.maps.Marker({
    position: myMap<%= i %>,
    map: map<%= i %>,
    title: 'Hello World!'
  });
  directionsDisplay<%= i %>.setMap(map<%= i %>);
  directionsDisplay<%= i %>.setPanel(document.getElementById('directions-panel<%= i %>'));

  showPosition<%= i %>();

}

function showPosition<%= i %>() {
  var end<%= i %> = "<%= raw location.lat %>,<%= raw location.lng %>";
  var start<%= i %> = "<%= raw @tour.locations[i+1].lat %>,<%= raw @tour.locations[i+1].lng %>";
  var request<%= i %> = {
      origin:start<%= i %>,
      destination:end<%= i %>,
      travelMode: google.maps.TravelMode.TRANSIT
  };
  directionsService<%= i %>.route(request<%= i %>, function(response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
      directionsDisplay<%= i %>.setDirections(response);
    }
  });
}

google.maps.event.addDomListener(window, 'load', initialize);

    </script>




<div id="map-canvas<%= i %>" style="min-width:300px; max-width: 80%; height:380px;"></div>
    <!-- <button onclick="showPosition()">Get Directions</button> -->

<div id="directions-panel<%= i %>" style="min-width:300px; max-width: 80%; " ></div>


<% end %>
<% end %>

</div>

app/views/tours/edit.html.erb
<%= form_for(@tour) do |f| %>
  <% if @tour.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tour.errors.count, "error") %> prohibited this tour from being saved:</h2>

      <ul>
      <% @tour.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>
    <%= f.label :category %>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
    <div class="field">

    <%# f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>

    <%= f.fields_for(:tags, Tag.new) do |tag_form| %>
      <p>Add a new tag:</p><br>
      <%= tag_form.label :name %>
      <%= tag_form.text_field :name %>
    <% end %>
  </div>
  <div class="field">
  <h1> Cities </h1>
    <%= f.fields_for(:cities, City.new) do |t| %>
    <%= t.label :name %><br>
    <%= t.text_field :name %><br>
    <% end %>
  </div>


  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/tours/guide_show.html.erb
<div class="tourImage">

<div class="tourDescription">
    <h1><%= @tour.title %></h1>
    <h4><%= @tour.description %></h4>
  </div>
</div>


<% if @tour.images.first %>
<style>
    .tourImage{
     background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(<%= @tour.images.first.image_url %>);
      background-color: black;
      background-size: cover;
      background-repeat: no-repeat;
      background-position: 50% 50%;
    }

    .thumb {
        background: url("http://ih1.redbubble.net/image.38250018.7772/flat,550x550,075,f.u1.jpg");
        width: 100px;
        height: 100px;
        background-position: center center;
        background-size: cover;
        background-repeat: no-repeat;
    }
    </style>
<% end %>

      <div class="tourImageFloat">
      
      <div class="userTourAvatar">
        <% if @tour.guide.images.count >= 1 %>
        <%=image_tag("#{@tour.guide.images.last.image_url}", size:"100x100")%>
  <% elsif @tour.guide.images.empty? %>        
  <div class="thumb" title="Portrait: 400x800"></div>
      <% else %>
    <h2><%= @tour.guide.name %></h2>
      <h3><%= link_to @tour.guide.name, @tour.guide %></h3>
      <p>(That's you!)</p>
   <% end %>
   </div>
         <div id="map" class="map"></div>
      </div>


<p id="notice"><%= notice %></p>




<div class="tourBodyContainer">

<div class="tourInfoContainer">
    <h4 style="margin-left:0">Tour score:</h4> <%= @tour.average_score %>

  <h4>Tags:</h4><p>
  <% @tour.tags.each do |tag| %>
  <%= tag.name %>
  <% end %>
  </p>

  <% if @tour.cities.count > 1 %>
<h4>Cities:</h4>
<% else %>
<h4>City:</h4>
<% end %>
  <% @tour.cities.each do |city| %>
  <%= city.accent %>
  <% end %>

  <br><br>
    <%= link_to "View Mobile Tour","#{@tour.id}/mobiletour?id=#{@tour.id}" %>
</div>


    <% @tour.locations.each do |location| %>
    <%= link_to "#{location.title}", tour_location_path(@tour,location) %><br>
    <%= location.address %><br><br>
    <%= link_to "Upload Content", "/tours/#{@tour.id}/locations/#{location.id}/content/?tour_id=#{@tour.id}", class: "linkBtnSmall" %>
    <%= link_to 'Edit', edit_tour_location_path(@tour,location), class: "linkBtnSmall" %>
    <%= link_to 'Delete', tour_location_path(@tour,location), method: :delete, class: "linkBtnSmall" %><br><br><br><br>
    <% end %>


<div class="grayBoxBG">
 <%= form_for [@tour, @location] do |f|  %>
 <%= f.hidden_field :tour_id, :value => @tour.id %>
    <%= f.label :title %><br>
    <%= f.text_field  :title %><br><br>
    <%= f.label :address %><br>
    <%= f.text_field  :address %><br><br><br>
    <%= f.submit "Add Location", class: "linkBtn" %>
 <%end%>
 </div>

<div class="grayBoxBG">  
<% if @tour.published && !@tour.locations.empty? %>
    <%= form_for [@tour, @comment] do |f| %>
       <%= f.label "Leave a comment for this tour: " %>
       <br>
       <%= f.text_field :content, style: "height: 30em; width: 70%" %>
       <br><br>
       <%= f.submit "Post", class: "linkBtn" %>
     <% end %>
  <% elsif !@tour.published && !@tour.locations.empty? %>
    <%= form_tag("/publish") %>
    <%= hidden_field_tag :id, @tour.id %>
    <%= submit_tag 'Publish this tour' %><br>
  <% else %>
    Create a location to publish the tour
  <% end %>

</div>
<%= link_to 'Edit', edit_tour_path(@tour), class: "linkBtnGray" %>
<%= link_to 'Back', tours_path, class: "linkBtnGray" %>

</div>


<% @locationsarr = [] %>
  <% @tour.locations.each do |location| %>
  <% @locationsarr << ["<a href=""></a><br><br>", location.lat.to_f,location.lng.to_f] %>
  <% end %>
</div>


<!--    <div id="map" style="opacity: 0.9;"></div> -->



<script src="http://jawj.github.com/OverlappingMarkerSpiderfier/bin/oms.min.js"></script>

  <script>
    // Define your locations: HTML content for the info window, latitude, longitude
    var locations = <%= raw @locationsarr.to_json %>;
    var iconURLPrefix = 'http://maps.google.com/mapfiles/ms/icons/';

    var icons = [
      iconURLPrefix + 'red-dot.png',
      iconURLPrefix + 'green-dot.png',
      iconURLPrefix + 'blue-dot.png',
      iconURLPrefix + 'orange-dot.png',
      iconURLPrefix + 'purple-dot.png',
      iconURLPrefix + 'pink-dot.png',
      iconURLPrefix + 'yellow-dot.png'
    ]
    var iconsLength = icons.length;

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 10,
      center: new google.maps.LatLng(40.7412,-73.9973),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      mapTypeControl: false,
      streetViewControl: false,
      panControl: false,
      zoomControlOptions: {
         position: google.maps.ControlPosition.LEFT_BOTTOM
      }
    });

    var oms = new OverlappingMarkerSpiderfier(map);

    var infowindow = new google.maps.InfoWindow({
      maxWidth: 160
    });

    var markers = new Array();

    var iconCounter = 0;

    // Add the markers and infowindows to the map
    for (var i = 0; i < locations.length; i++) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map,
        icon: icons[iconCounter]
      });

      markers.push(marker);
      oms.addMarker(marker);

      google.maps.event.addListener(marker, 'mouseover', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));

      iconCounter++;
      // We only have a limited number of possible icon colors, so we may have to restart the counter
      if(iconCounter >= iconsLength) {
        iconCounter = 0;
      }
    }

    function autoCenter() {
      //  Create a new viewpoint bound
      var bounds = new google.maps.LatLngBounds();
      //  Go through each...
      for (var i = 0; i < markers.length; i++) {
        bounds.extend(markers[i].position);
      }
      //  Fit these bounds to the map
      map.fitBounds(bounds);
    }
    autoCenter();
  </script>

app/views/tours/imageupload.html.erb
Add your Image here!
<%= direct_upload_form_for @uploader do |f| %>
  <%= f.file_field :image %>
  <%= f.submit %>
<% end %>

app/views/tours/new.html.erb
<div class="grayBoxBG horizontalCenter" style="width: 30em">

<h1>Create New Tour</h1>
<%= form_for(@tour) do |f| %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %><br>
    <br>
    <%= f.label :description %><br>
    <%= f.text_area :description %><br>
    <br>
    <%= f.label :category %><br><br>
    <%= f.collection_select :category_id, Category.all, :id, :name %>
  </div>
  <div class="field">
  <%# f.collection_check_boxes :tag_ids, Tag.all, :id, :name %><br>
  <%= f.fields_for(:tags, Tag.new) do |tag_form| %>
    <p>Add tags:</p>
    <%= tag_form.text_field :name, id: 'singleFieldTags' %>
  <% end %>
  </div>

    <div class="field">
  <h4> Cities </h4>
    <%= f.fields_for(:cities, City.new) do |t| %>
    <%= t.label :name %><br>
    <%= t.text_field :name, id: 'autocompletecity' %><br>
    <% end %>
  </div>
  <div class="actions">
  <br><br><br>
    <%= f.submit class: "linkBtn" %>
  </div>
<% end %>



<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>

<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/flick/jquery-ui.css">
<%= stylesheet_link_tag 'jquery.tagit' %>

  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.5.2/jquery.min.js" type="text/javascript" charset="utf-8"></script>
  <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.12/jquery-ui.min.js" type="text/javascript" charset="utf-8"></script>

  <%= javascript_include_tag 'tag-it.js' %>


<script>
$( "#autocompletecity" ).autocomplete({
  source: <%= raw City.pluck(:name) %>
});
</script>

<script>
        $(function(){
            var sampleTags = <%= raw Tag.pluck(:name) %>;
            // Single field
            //-------------------------------
            $('#singleFieldTags').tagit({
                availableTags: sampleTags,
                // This will make Tag-it submit a single form value, as a comma-delimited field.
                singleField: true,
                allowSpaces: true,
                singleFieldNode: $('#mySingleField')
            });
        });
    </script>

    </div>

app/views/tours/non_participants_show.html.erb
<div class="tourImage">

<div class="tourDescription">
    <h1><%= @tour.title %></h1>
    <h4><%= @tour.description %></h4>
  </div>
</div>



<% if @tour.images.first %>
<style>
    .tourImage{
     background: linear-gradient( rgba(0, 0, 0, 0.5), rgba(0, 0, 0, 0.5) ), url(<%= @tour.images.first.image_url %>);
      background-color: black;
      background-size: cover;
      background-repeat: no-repeat;
      background-position: 50% 50%;
      display: inline-block;
    }

    .thumb {
        background: url("http://ih1.redbubble.net/image.38250018.7772/flat,550x550,075,f.u1.jpg");
        width: 100px;
        height: 100px;
        border-radius: 50%;
        background-position: center center;
        background-size: cover;
        background-repeat: no-repeat;
    }
    </style>
<% end %>




   <div class="tourImageFloat">
      <div class="userTourAvatar">
  <% if @tour.guide.images.count >= 1 %>
  <%=image_tag("#{@tour.guide.images.last.image_url}", size:"100x100")%>
  <% elsif @tour.guide.images.empty? %>
        <div class="thumb" title="Portrait: 400x800"></div>
    <% else %>
    <h2><%= @tour.guide.name %></h2>
    <%= link_to "Edit Profile", edit_user_path %><br>
  <% end %>
      <h3><%= link_to @tour.guide.name, @tour.guide %></h3>

    <% if user_signed_in? %>
      <br>
      <%# link_to "Message Me", new_conversation_path, class: "linkBtn"  %>
      <%= form_tag("/conversations/new",method: "get") do %>
      <%= hidden_field_tag(:friend_id, @tour.guide.id) %>
      <%= submit_tag("Message Me", class: "linkBtnGray")%>
      <% end %>
      <br>
      <% if !current_user.friends.include?(@tour.guide) && !current_user.pending_friends.include?(@tour.guide)  %>
      <%= link_to "Add Friend", friendships_path(:friend_id => @tour.guide), class: "linkBtn", :method => :post%>
      <% end %>
    <% end %>

      </div>
      <div id="map" class="map"></div>

    </div>




</div>
</div>




<div class="tourBodyContainer">

<div class="tourInfoContainer">
    <h4 style="margin-left:0">Tour score:</h4> <%= @tour.average_score %>

  <h4>Tags:</h4><p>
  <% @tour.tags.each do |tag| %>
  <%= tag.name %>
  <% end %>
  </p>

  <% if @tour.cities.count > 1 %>
<h4>Cities:</h4>
<% else %>
<h4>City:</h4>
<% end %>
  <% @tour.cities.each do |city| %>
  <%= city.accent %>
  <% end %>

  <br><br>
</div>


<p id="notice"><%= notice %></p>

<% @tour.reviews.each do |review| %>
  <div class="grayBoxBG">
  <h3>Rated: <%= review.rating %>/5</h3>
  <%= review.content %>
  </div>
<% end %>
 <% if user_signed_in? %>
   <%= form_tag("/participate") %>
   <%= hidden_field_tag(:user_id, current_user.id) %>
   <%= hidden_field_tag(:id, @tour.id) %>
   <%= submit_tag("Participate", class: "linkBtn") %>
 <% else %>
   <%= link_to "Log In", new_user_session_path %>
   or
   <%= link_to "Sign Up", new_user_registration_path %>
   To Participate
 <% end %><br>

</div>

<% @locationsarr = [] %>
  <% @tour.locations.each do |location| %>
  <% @locationsarr << ["<a href=""></a><br><br>", location.lat.to_f,location.lng.to_f] %>
  <% end %>
</div>

<script src="http://jawj.github.com/OverlappingMarkerSpiderfier/bin/oms.min.js"></script>

  <script>
    // Define your locations: HTML content for the info window, latitude, longitude
    var locations = <%= raw @locationsarr.to_json %>;
    var iconURLPrefix = 'http://maps.google.com/mapfiles/ms/icons/';

    var icons = [
      iconURLPrefix + 'red-dot.png',
      iconURLPrefix + 'green-dot.png',
      iconURLPrefix + 'blue-dot.png',
      iconURLPrefix + 'orange-dot.png',
      iconURLPrefix + 'purple-dot.png',
      iconURLPrefix + 'pink-dot.png',
      iconURLPrefix + 'yellow-dot.png'
    ]
    var iconsLength = icons.length;

    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 13,
      center: new google.maps.LatLng(40.7412,-73.9973),
      mapTypeId: google.maps.MapTypeId.ROADMAP,
      mapTypeControl: false,
      streetViewControl: false,
      panControl: false,
      zoomControlOptions: {
         position: google.maps.ControlPosition.LEFT_BOTTOM
      }
    });

    var oms = new OverlappingMarkerSpiderfier(map);

    var infowindow = new google.maps.InfoWindow({
      maxWidth: 160
    });

    var markers = new Array();

    var iconCounter = 0;

    // Add the markers and infowindows to the map
    for (var i = 0; i < locations.length; i++) {
      var marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map,
        icon: icons[iconCounter]
      });

      markers.push(marker);
      oms.addMarker(marker);

      google.maps.event.addListener(marker, 'mouseover', (function(marker, i) {
        return function() {
          infowindow.setContent(locations[i][0]);
          infowindow.open(map, marker);
        }
      })(marker, i));

      iconCounter++;
      // We only have a limited number of possible icon colors, so we may have to restart the counter
      if(iconCounter >= iconsLength) {
        iconCounter = 0;
      }
    }

    function autoCenter() {
      //  Create a new viewpoint bound
      var bounds = new google.maps.LatLngBounds();
      //  Go through each...
      for (var i = 0; i < markers.length; i++) {
        bounds.extend(markers[i].position);
      }
      //  Fit these bounds to the map
      map.fitBounds(bounds);
    }
    autoCenter();
  </script>

app/views/tours/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Title:</h3>
<%= @tour.title %>
<h3>Description:</h3>
<%= @tour.description %>
<h3>Tags:</h3>
<ul>
  <% @tour.tags.each do |tag| %>
  <li><%= tag.name %></li>
  <% end %>
</ul>
<br>
<h3>Cities:</h3>
<ul>
  <% @tour.cities.each do |city| %>
  <li><%= city.accent %></li>
  <% end %>
</ul>

<h3>Locations:</h3>
<ul>
  <% @tour.locations.each do |location| %>
  <li><%= location.title %></li>
  <li><%= location.address %></li>
  <%= link_to 'Edit', edit_tour_location_path(@tour,location) %>
  <%= link_to 'Delete', tour_location_path(@tour,location), method: :delete %>
  <% end %>
</ul>

 <%= form_for [@tour, @location] do |f|  %>
 <%= f.hidden_field :tour_id, :value => @tour.id %>
    <%= f.label :title %>
    <%= f.text_field  :title %>
    <%= f.label :address %>
    <%= f.text_field  :address %>
    <%= f.submit "Create Location" %>
 <%end%>

 <%# @tour.comments.each do |comment| %>
 <%#= comment.content %>
 <%# end %>

<%= link_to 'Edit', edit_tour_path(@tour) %> |
<%= link_to 'Back', tours_path %>